### ISSUE TITLE
Graphcast run fails (for me) at dict_merge

### ISSUE THREAD

**Issue by Dadoof** [ecmwf-lab/ai-models-graphcast#1]
Good day all,

Giving graphcast a go, nearly there, but ended up with this:
 ai-models --date 20230906 --time 0000 --input cds --assets grc graphcast
 
  File "/usr/local/lib/python3.10/site-packages/cfgrib/dataset.py", line 753, in open_fieldset
    return open_from_index(filtered_index, read_keys, time_dims, extra_coords, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/cfgrib/dataset.py", line 729, in open_from_index    dimensions, variables, attributes, encoding = build_dataset_components(
  File "/usr/local/lib/python3.10/site-packages/cfgrib/dataset.py", line 683, in build_dataset_components
    dict_merge(variables, coord_vars)
  File "/usr/local/lib/python3.10/site-packages/cfgrib/dataset.py", line 614, in dict_merge    raise DatasetBuildError(
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='time' value=Variable(dimensions=('time',), data=array([1693936800,1693958400])) new_value=Variable(dimensions=('time',), data=array([1693893600, 1693936800]))

Full log file (with debug set to on) below:
[gcd.txt](https://github.com/ecmwf-lab/ai-models-graphcast/files/12623440/gcd.txt)

A log file with the output of the build process (showing which packages got installed) below:
[gcb.txt](https://github.com/ecmwf-lab/ai-models-graphcast/files/12623539/gcb.txt)

**Comment by Dadoof** [comment]
Attempt, below, to provide a log file of output - with 'debug' turned on
[gcd.txt](https://github.com/ecmwf-lab/ai-models-graphcast/files/12623444/gcd.txt)

**Comment by idharssi2020** [comment]
I get the same error with command
`ai-models --input cds --date 20230101 --time 0000 graphcast`

reporting error
`cfgrib.dataset.DatasetBuildError: key present and new value is different: key='time' value=Variable(dimensions=('time',), data=array([1672509600, 1672531200])) new_value=Variable(dimensions=('time',), data=array([1672466400, 1672509600]))`

**Comment by jacob-radford** [comment]
Confirming I get the same error with @idharssi2020's command. Any ideas here?

**Comment by mchantry** [comment]
Thanks for the feedback, we are investigating this issue and will provide an update soon.

**Comment by Dadoof** [comment]
To all: In the past, when I went through the installation process, I started with python 3.10.13. That built all the pieces.
Today, I attempted to build starting from python 3.11.6, and it did not build at all. Got stuck in a few of the pip moments.

**Comment by Dadoof** [comment]
Hello all,

It does appear that the error I, and others, posted comes from the precipitation fields in the grib files as downloaded from CDS.

What I get from CDS is the 5-6 hour forecast with an end time that matches the analysis time. It appears that this is not what the code wants.

Commenting out 'tp' in /.local/lib/python3.10/site-packages/ai_models_graphcast/convert.py got me around the error above, but then the model does not work as the field is missing.

To the ECMWF folks: I am pretty sure that the download of the precip 'analysis' is what needs fixing.

**Comment by b8raoult** [comment]
We have updated the code. Can you try again?

**Comment by Dadoof** [comment]
Hello there,

I gave it a go, but no change in the results. I am wondering if I am not getting the latest version.

I do this:
git clone https://github.com/ecmwf-lab/ai-models.git

Then later this:
pip3 install ai-models-graphcast
git clone https://github.com/ecmwf-lab/ai-models-graphcast.git
cd ai-models-graphcast
pip3 install -r requirements-gpu.txt -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

Unsure if I need any special tag to get the revised code.

Regards,
Brian E.

**Comment by b8raoult** [comment]
It you clone the code, don't install from pipy as well.

```
cd ~/git
git clone https://github.com/ecmwf-lab/ai-models.git
cd ai-models
pip3 install --upgrade -e .
```

and

```
cd ~/git
git clone https://github.com/ecmwf-lab/ai-models-graphcast.git
cd ai-models-graphcast
pip3 install --upgrade -e .
pip3 install -r requirements-gpu.txt -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```

**Comment by b8raoult** [comment]
If you already have cloned the code

```
cd ~/git/some-repo
git pull
pip3 install --upgrade -e .
```

**Comment by Dadoof** [comment]
Good afternoon (morning here in Colorado),

I have made the changes you suggested. They did indeed get me to the most recent/latest version.
Ran things on this hardware: NVIDIA Tesla V100 (on AWS)

Ran using this command:
ai-models --date 20230927 --time 0000 --input cds --assets grc graphcast 

Sadly I ran out of memory, I shall try again to get beefier hardware.

**Comment by Sardingfish** [comment]
Hello, I also encountered this problem, "jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory allocating 163104825552 bytes. ", which equates to 152Gb of memory required, does this mean that PCs can't run graphcast?

**Comment by idharssi2020** [comment]
I get a similar error message, I'm trying the suggestions in https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html

**Comment by Dadoof** [comment]
To all: I also did those exports above, and can comfirm that, plus increasing my memory, led to success.

**Comment by Sardingfish** [comment]
Can I ask what your total memory was after you increased it?

**Comment by idharssi2020** [comment]
![image](https://github.com/ecmwf-lab/ai-models-graphcast/assets/80441682/ebaf6009-d69c-4fcb-bcf0-5cfb2c3d35f8)

An example plot from running graphcast in near real time.

**Comment by Dadoof** [comment]
> Can I ask what your total memory was after you increased it?

I have been running on Amazon, AWS. I was not able to do so with their 'p3' instance, but was with their 'p5' instance.
![p5](https://github.com/ecmwf-lab/ai-models-graphcast/assets/144810245/3ec29110-379a-45cb-9d89-0ceb4a82f6cc)

**Comment by Dadoof** [comment]
As it does work on the p5 instance, this ticket is hereby closed.
