### ISSUE TITLE
1 hour predictions with graphcast

### ISSUE THREAD

**Issue by iluise** [ecmwf-lab/ai-models-graphcast#11]
I would like to modify the module to get hourly predictions from graphcast:

So, what I have done was to change just the `steps` and the `lagger` to 1 here:
https://github.com/ecmwf-lab/ai-models-graphcast/blob/main/ai_models_graphcast/model.py#L87-L88

But I am not sure about how to change the lines here:
https://github.com/ecmwf-lab/ai-models-graphcast/blob/main/ai_models_graphcast/model.py#L277-L284

Is it correct to use the `scda` stream for all the values  with % 12 != 0 ? Because at the moment I get the plot I post below. 
Thanks in advance. 

<img width="749" alt="Screenshot 2024-03-04 at 17 43 32" src="https://github.com/ecmwf-lab/ai-models-graphcast/assets/72020169/f0a1ad32-262d-4e01-aba6-fa005b749ed4">

**Comment by mchantry** [comment]
Hello.
It is not possible to get 1hour predictions from GraphCast. The model steps forward in 6h increments. I do not see any way, without retraining, to get a 1-hour prediction.

**Comment by iluise** [comment]
Yeah, small misunderstanding within the team :) Sorry for the noise.
Best, 

Ilaria
