### ISSUE TITLE
Pip install error

### ISSUE THREAD

**Issue by aaron-kaijser** [ecmwf-lab/ai-models-graphcast#6]
Trying to pip install w/ Python 3.10 in a virtual environment is failing. I installed earthkit-meteo and tried it again but it doesn't work. Pip is running with the latest version (23.3.1).

pip install ai-models-graphcast
Collecting ai-models-graphcast
  Using cached ai-models-graphcast-0.0.4.tar.gz (12 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting ai-models>=0.2.3 (from ai-models-graphcast)
  Using cached ai-models-0.2.15.tar.gz (20 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: earthkit-meteo in c:\graphcast\.venv\lib\site-packages (from ai-models-graphcast) (0.0.1)
Collecting dm-tree (from ai-models-graphcast)
  Using cached dm_tree-0.1.8-cp310-cp310-win_amd64.whl (101 kB)
Collecting entrypoints (from ai-models>=0.2.3->ai-models-graphcast)
  Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
Collecting climetlab<=0.18.6,>=0.17.1 (from ai-models>=0.2.3->ai-models-graphcast)
  Using cached climetlab-0.18.6.tar.gz (195 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting multiurl (from ai-models>=0.2.3->ai-models-graphcast)
  Using cached multiurl-0.2.3.2.tar.gz (17 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
**INFO: pip is looking at multiple versions of ai-models to determine which version is compatible with other requirements. This could take a while.**
Collecting ai-models>=0.2.3 (from ai-models-graphcast)
  Using cached ai-models-0.2.14.tar.gz (20 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting climetlab>=0.17.1 (from ai-models>=0.2.3->ai-models-graphcast)
  Using cached climetlab-0.19.0.tar.gz (177 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting ai-models>=0.2.3 (from ai-models-graphcast)
  Using cached ai-models-0.2.13.tar.gz (20 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached ai-models-0.2.11.tar.gz (19 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached ai-models-0.2.10.tar.gz (19 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached ai-models-0.2.9.tar.gz (19 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached ai-models-0.2.8.tar.gz (19 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached ai-models-0.2.7.tar.gz (19 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
**INFO: pip is still looking at multiple versions of ai-models to determine which version is compatible with other requirements. This could take a while.**
  Using cached ai-models-0.2.6.tar.gz (19 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached ai-models-0.2.5.tar.gz (19 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached ai-models-0.2.3.tar.gz (18 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting ai-models-graphcast
  Using cached ai-models-graphcast-0.0.3.tar.gz (11 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
**INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.**
  Using cached ai-models-graphcast-0.0.2.tar.gz (11 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
**ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
ai-models-graphcast depends on earthkit-meteo@ git+https://github.com/ecmwf/earthkit-meteo.git@48deab9#egg=earthkit-meteo**

**Comment by HCookie** [comment]
This has been addressed with recent releases of `earthkit.data`.
