### ISSUE TITLE
GraphCast Precipitation

### ISSUE THREAD

**Issue by jacob-t-radford** [ecmwf-lab/ai-models-graphcast#8]
The precipitation output from GraphCast in the ai-models implementation is total accumulation since forecast hour 5 according to the grb messages - can you explain why it's accumulated from hour 5 instead of hour 0?

**Comment by mchantry** [comment]
Hi Jacob, this is a labelling error.

**Comment by jacob-t-radford** [comment]
Great, thank you for the quick response!

**Comment by b8raoult** [comment]
This should be fixed in version 0.0.5 of the plugin.
